# Generated by Django 3.1 on 2020-09-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
