# Generated by Django 3.1 on 2020-09-09 11:33

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200909_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=200, validators=[courses.models.course_name_validator]),
        ),
        migrations.AlterField(
            model_name='course',
            name='url_name',
            field=models.SlugField(editable=False, max_length=200, unique=True),
        ),
    ]
