# Generated by Django 3.1 on 2020-09-10 07:17

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200909_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, validators=[courses.models.name_validator])),
                ('session_description', models.CharField(max_length=2000)),
                ('url_name', models.SlugField(editable=False, max_length=200, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
