# Generated by Django 3.1 on 2020-09-10 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_basesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('basesession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.basesession')),
            ],
            bases=('courses.basesession',),
        ),
    ]
