# Generated by Django 3.1 on 2020-09-10 08:00

import courses.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200910_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200, validators=[courses.models.name_validator])),
                ('session_description', models.CharField(max_length=2000)),
                ('session_content', models.CharField(max_length=20000)),
                ('url_name', models.SlugField(editable=False, max_length=200, unique=True)),
                ('session_duration', models.DurationField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
