# Generated by Django 3.1 on 2020-09-24 12:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lecturesession_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturesession',
            name='session_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
